### ISSUE TITLE
Alpha channel turns black

### ISSUE THREAD

**Issue by jacobtomlinson** [furagu/easy-gd#4]
Thanks for this library, it's great!

One problem I've found when adding watermarks to PNGs with transparency is that the transparency turns black.

Any ideas on how to fix this?

**Comment by furagu** [comment]
Hey! Good to hear you liked the library.

Actually it should handle the transparency correctly.
So, could you provide some sample files and code? I can take a look and just fix that.

**Comment by jacobtomlinson** [comment]
Yeah no problem, I'll just strip out some example code.

**Comment by jacobtomlinson** [comment]
#### Original files
input.png
![dog_png2414](https://cloud.githubusercontent.com/assets/1610850/9364750/ce88cfce-46a5-11e5-870a-d4537fe2c373.png)
smiley.png
![smiley](https://cloud.githubusercontent.com/assets/1610850/9364756/d693a8f6-46a5-11e5-8d9c-e38ee680e444.png)

#### Code
```
    var outStream = fs.createWriteStream('/tmp/output.png')
    fs.createReadStream('/tmp/input.png')
        .pipe(gd.watermark('/tmp/smiley.png', {x: 1, y: 0.9}))
        .pipe(outStream)
```

#### Result
![ea9b0c65c1](https://cloud.githubusercontent.com/assets/1610850/9364794/fe9a0b74-46a5-11e5-8bc9-1e0d67be3e21.png)

**Comment by jacobtomlinson** [comment]
Any update on this? Thanks!

**Comment by jacobtomlinson** [comment]
Bump

**Comment by furagu** [comment]
@jacobtomlinson sorry man, was busy the whole weekend. Will take a look tonight.

**Comment by jacobtomlinson** [comment]
Awesome thanks!

**Comment by jacobtomlinson** [comment]
Great thank you very much.

**Comment by furagu** [comment]
You are welcome!
The updated version is already available via npm.

By the way, your smiley.png has a white opaque background, which was kinda confusing :)
Anyway,  now that works:

```
var gd = require('./index.js'),
    fs = require('fs')

var outStream = fs.createWriteStream('out.png')

fs.createReadStream('in.png')
    .pipe(gd.watermark( gd.open('in.png').resize({width: 200, height: 200}) ))
    .pipe(gd.watermark('s.png'))
    .pipe(outStream)
```

![out](https://cloud.githubusercontent.com/assets/832976/9460548/89e318be-4b07-11e5-81ab-609f9b352df0.png)

**Comment by jacobtomlinson** [comment]
Ah thanks. I just grabbed that smiley off the interwebs for the example, I'm not actually using it.
