### ISSUE TITLE
Read image dimension

### ISSUE THREAD

**Issue by mhipo1364** [furagu/easy-gd#6]
Hi

I need to read image dimension for validity. How can I access to image dimension ?

I can't access them using `exif`, so how can I do this?

**Comment by furagu** [comment]
Hey!

The library itself is a wrapper around node-gd, so everything you can find in the [node-gd documentation](https://www.npmjs.com/package/node-gd) is applicable to easy-gd as well.

Here is the way to get image dimensions:

``` javascript
var image = gd.open('my-image.jpeg') //could also be asynchronous with a callback

image.width
image.height
```

**Comment by mhipo1364** [comment]
@furagu : Thanks man, saved my time so much :+1:
